name: CI

on: 
  schedule:
    - cron: '0 14 * * 1'
  pull_request:
    types: [opened, synchronize]
    branches: [main, beta]

jobs:
  init:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/setup-node
      - uses: wagoid/commitlint-github-action@v4
        env:
          NODE_PATH: ${{ github.workspace }}/node_modules

  validate:
    needs: init
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/setup-node

      - name: validate (lint)
        run: |
          yarn lint --no-deps --scope="@chakra-icons/*" --scope="create-*" --parallel 

  test:
    needs: init
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/setup-node

      - name: run test
        run: yarn test 

  build:
    needs: init
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/setup-node
      
      - name: build project
        run: yarn build

  sync:
    needs: build
    runs-on: ubuntu-latest
      # if: ${{ github.event_name == 'schedule' }}
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/setup-node

      - run: git checkout -B feat/sync-icons

      - name: create commit when changed snapshot.json in @chakra-icons/*
        run: ./.github/scripts/sync-snapshot

      - run: git push origin feat/sync-icons

      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.GH_TOKEN }}
          branch: feat/sync-icons

      - name: Information
        if: ${{ steps.cpr.outputs.pull-request-number }}
        run: |
          echo "Pull Request Number - ${{ steps.cpr.outputs.pull-request-number }}"
          echo "Pull Request URL - ${{ steps.cpr.outputs.pull-request-url }}"
